# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  emailsenderdemo:
    image: emailsenderdemo
    environment: 
      - SMTP_USER=xxxx@gmail.com
      - SMTP_PASS=xxxxx
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
